#!/bin/bash
#
#	Description:	Changes among existing grub2 themes
#	Lisence:        GPL v3
#	Author:         Simon A. Erat (sea)
#	Release Date:   2012.12.23
#	Changed Date:	2013.06.28
	script_version=0.5
#
#	Title
#
	if [ ! -f /usr/share/script-tools/st.cfg ]
	then	alias sT="echo"
		alias sP="printf"
		alias sE="echo"
		SUCCESS="[ yay :) ]"
		FAILURE="[ noo :( ]"
		PROGRESS="[ wait.. ]"
	fi
	sT "sea's Grub2 Theme changer ($script_version)"
	[ ! 0 -eq $UID ] && sE "Script requires root rights!" && return 1
#
#	Variables
#
	def=/etc/default/grub
	dir_themes=/boot/grub2/themes/
	dir_themes_d=""
	for d in $(ls $dir_themes);do [ -d "$dir_themes/$d" ] && dir_themes_d="$dir_themes_d $d";done
#
#	Looking for existing entry
#	
	line="$(grep GRUB_THEME $def)"
	current=$(echo "$line"|sed s/"="/" "/g|sed s/\"/' '/g|awk '{print $2}')
	case "${line:0:1}" in
	"#")	current=disabled	;;
	"G")	current="$(basename $(dirname $current))"	;;
	"")	current=none	;;
	esac
#
#	Display
#
	sE "The current theme is:" "$(Capitalize $current)"
	if ask "Do you want to change it?"
	then	sE "Please select your new GRUB theme:"
		select entry in Back Toggle $dir_themes_d
		do 	[ "$entry" = "Back" ] && return 0
			sE "Selected theme:" "$entry"
			break
		done
#
#	Fix strings
#
		case $entry in
		Toggle)	[ disabled = "$current" ] && REPL="${line:1}" || REPL="#$line"	;;
		*)	REPL="GRUB_THEME=\"/boot/grub2/themes/$entry/theme.txt\""
			[ "#" = "${REPL:1}" ] && REPL="${REPL:1}" 			;;
		esac
#
#	Save setting
#
		if [ ! "" = "$(echo $line)" ]
		then	sed s\\$line\\$REPL\\g -i $def && \
			retval=0 || retval=1
		else	echo "$REPL" >> $def && \
			retval=0 || retval=1
		fi
	#
	#	Rebuild GRUB Menu, if successfull
	#
		if [ 0 -eq $retval ]
		then	sE ""
			ask "Rebuild GRUB2?" && \
			grub2-mkconfig -o /boot/grub2/grub.cfg > /dev/zero && \
			return 0
		fi
		return 1
	else	sE "" "$BACK"
		return 0
	fi
