#!/bin/bash
#
# 	sea's "dev prj new" is aimed to assist developers to  
# 	easy handle their multiple projects.
#
# 	This script is written with best intention to help, 
# 	but there is NO warranty or garanty and I deny ANY responsiblity
# 	that may or may not affect your system.
#
#
# 	Lisence:        GPL v3
# 	Author:         Simon A. Erat (sea)
# 	Release Date:   2012 June 25
# 	Changed Date:	2013 July 31
  	script_version=0.2
#
#
#	Title
#
	title="sea's Project Manager - New project"
	sT "$title ($script_version)"
#
#	Vars
#
	lbl=""
	list="$(ls $SEA_DEV_DIR)"
#
#	Figure label 
#
	sE "Current projects:" "$(echo $list)"
	[ -z $4 ] && \
		lbl=$(input "Please type a new project label: ") || \
		lbl=$4
	PRJ_New $lbl
	ReportStatus $? "Created new project: $lbl"
