#!/bin/bash
tui-title "Update GRUB2"
[ ! 0 -eq $UID ] && sE "Requires root access!" "FAIL" && return 1

current_distro=$(distro|awk '{print $1}')
grub_efi=/boot/efi/EFI/${current_distro,,}/grub.cfg

[ -f $grub_efi ] && OUTFILE=$grub_efi || OUTFILE=/boot/grub2/grub.cfg

grub2-mkconfig -o $OUTFILE