#!/bin/bash
#
#	Desription:	Edit koji project
#	Lisence:        GPL v3
#	Author:         Simon A. Erat (sea), erat.simon æ gmail.com
#	Release Date:   2012.11.16
#	Changed Date:	2013.08.28
	script_version=0.5
#
#	Title
#
	title="sea's Koji Handler - Edit"
	sT "$title ($script_version)"
#
#	Variables
#
	lbl=""
	[ ! -z $4 ] && \
		[ -f "$SEA_DEV_DIR/$4/conf" ] && \
		lbl="$4"
	[ "" = "$lbl" ] && \
		sP "Please select a LABEL to use:" && \
		lbl=$(PRJ_Select) && \
		sE "Selected $lbl" "$DONE"
	[ ! -f "$SEA_DEV_DIR/$lbl/rpm" ] && \
		ReportStatus 1 "Project requires 'rpm'" && \
		return 1
	source "$SEA_DEV_DIR/$lbl/conf"
#
#	Display
#
	sEdit "$SEA_DEV_DIR/$lbl/koji"
	ReportStatus $? "Edited koji configuration for $prj_name"
