#!/bin/bash
#
#	Desription:	Edit rpm spec
#	Lisence:        GPL v3
#	Author:         Simon A. Erat (sea), erat.simon æ gmail.com
#	Release Date:   2012.11.16
#	Changed Date:	2013.07.31
	script_version=0.4
#
#	Title
#
	title="sea's RPM Handler - Edit changelog"
	sT "$title ($script_version)"
#
#	Variables
#
	lbl=""
	[ ! -z $5 ] && \
		[ -d $SEA_DEV_DIR/$5 ] && \
		lbl=$5
	[ "" = "$lbl" ] && \
		sP "Please select a LABEL to use:" && \
		lbl=$(PRJ_Select) && \
		sE "Selected $lbl" "$DONE"
	source "$SEA_DEV_DIR/$lbl/conf"
	source "$SEA_DEV_DIR/$lbl/rpm"
#
#	Display
#
	ask "Add a new 'release-header' for $prj_name?" && \
		AddChangelog $lbl || \
		sEdit "$rpm_changelog"
	ReportStatus $? "Edited $prj_name rpm changelog"
