#!/bin/bash
#
#	Description:	Display diffrent styles of bash colors
# 	Changed by:	sea
#	File created:	2012.06.15
#	File changed:	2013.08.26
	script_version=0.2
#
#	Variables
#
	# SCHEMA: DESCRIPTOR by ARTIST_AS_COMMAND
	menu=( "Light-dark-table-lists by bashguru" "Table by PabloTwo" "Textlist by EdwardsResearch" )
	title="Diffrent ways to display bash colors ($script_version)"
	seaconf=/usr/share/script-tools/st.cfg
#
#	Help
#
	[ "-h" = "$1" ] && \
		echo -e "$(basename $0) ($script_version)
		\rDisplay diffrent approaches of color shemes
		\r" && exit 99
#
#	Subs
#
	PabloTwo() { 
	# PabloTwo, as posted on http://forums.fedoraforum.org/showthread.php?t=
	# Reused as CC.
		#clear
		echo Table for 16-color terminal escape sequences.
		echo Replace ESC with \\033 in bash.
		echo
		echo "Background | Foreground colors"
		echo "---------------------------------------------------------------------"
		for((bg=40;bg<=48;bg++)); do
			for((bold=0;bold<=1;bold++)) do
				echo -en "\033[0m"" ESC[${bg}m   | "
				for((fg=30;fg<=37;fg++)); do
					if [ $bold == "0" ]; then
						echo -en "\033[${bg}m\033[${fg}m [${fg}m  "
					else
						echo -en "\033[${bg}m\033[1;${fg}m [1;${fg}m"
					fi
				done
				echo -e "\033[0m"
			done
			echo "--------------------------------------------------------------------- "
		done
		echo
	}
	EdwardsResearch() {
	# http://blog.edwards-research.com/2012/03/script-to-show-all-fontbackground-colors-in-bash/
	# Reused as CC.
		# The syntax for escaped color sequences looks like:
		#
		#    BLUE="\[\033[0;34m\]"
		#
		# Lets see what we can find...
		echo -e "\n\thttp://blog.edwards-research.com/2012/03/script-to-show-all-fontbackground-colors-in-bash\n"
		 
		NONE="\033[0m"
		 
		for COLOR in $(seq 30 40) ; do
		    for STYLE in $(seq 0 1) 4 5 7; do
			TAG="\033[${STYLE};${COLOR}m"
			STR="Color:${COLOR}--Style:${STYLE}"
		 
			echo -ne "${TAG}${STR}${NONE}  "
		    done
		    echo
		done
	}
	bashguru() {
	# http://www.bashguru.com/2010/01/shell-colors-colorizing-shell-scripts.html
	# Reused as CC.
		echo -e "\n\thttp://www.bashguru.com/2010/01/shell-colors-colorizing-shell-scripts.html\n"
		
		echo -e "\n\033[4;31mLight Colors\033[0m  \t\t\033[1;4;31mDark Colors\033[0m"
		# ---------------------------------------------------------------------------
		echo -e "\e[0;30;47m Black    \e[0m 0;30m \t\e[1;30;40m Dark Gray  \e[0m 1;30m"
		echo -e "\e[0;31;47m Red      \e[0m 0;31m \t\e[1;31;40m Dark Red   \e[0m 1;31m"
		echo -e "\e[0;32;47m Green    \e[0m 0;32m \t\e[1;32;40m Dark Green \e[0m 1;32m"
		echo -e "\e[0;33;47m Brown    \e[0m 0;33m \t\e[1;33;40m Yellow     \e[0m 1;33m"
		echo -e "\e[0;34;47m Blue     \e[0m 0;34m \t\e[1;34;40m Dark Blue  \e[0m 1;34m"
		echo -e "\e[0;35;47m Magenta  \e[0m 0;35m \t\e[1;35;40m DarkMagenta\e[0m 1;35m"
		echo -e "\e[0;36;47m Cyan     \e[0m 0;36m \t\e[1;36;40m Dark Cyan  \e[0m 1;36m"
		echo -e "\e[0;37;47m LightGray\e[0m 0;37m \t\e[1;37;40m White      \e[0m 1;37m"
	}
#
#	script-tools check
#
	#clear
	if [ ! -f $seaconf ]
	then	# No script tools, basic handling
		echo -e "\n\t$title\n\n"
		echo "Select an option to display bash-colors:"
		select entry in Back "${menu[@]}";do
			[ Back = "$entry" ] && exit
			cmd="$(echo $entry|awk '{print $3}')"
			$cmd
		done
	else	# Script tools available, full support
		source "$seaconf"
		sT "$title"
		sE "Select an option to display bash-colors:"
		select entry in Back "${menu[@]}";do
			[ Back = "$entry" ] && exit
			cmd="$(echo $entry|awk '{print $3}')"
			$cmd
		done
	fi
