#!/bin/bash
#
#	License:	GPL v3
#	Description:	Pings one time - a random url if no IP is provided
#	Author: 	Simon A. Erat, erat.simon æ gmail . com
#	Date created:	2012.11.14
#	Date changed:	2014.01.31
	script_version=0.4
#
#	Help
#
	[ "-h" = "$1" ] && \
		echo -e "$(basename $0) ($script_version)
		\rPings one time - a random url if no IP is provided
		\rUsage: $(basename $0) [URL]
		\r" && exit 99
#
#	Variables
#
	source /usr/share/script-tools/functions/system.math.rnd
	cmd="ping -c1"
	urls=('web.de' 'google.com' 'yahoo.com' 'redhat.com' 'ubuntu.com' 'fedoraforum.org' 'fedoraproject.org' 'archlinux.org' 'linux.com' 'sourceforge.com' )
#
#	Display
#
	sleep 0.3
	if [ -z $1 ]
	then	$cmd ${urls[$(rnd ${#urls[@]})]}
	else	$cmd $1
	fi
