#!/bin/bash
#
#	sea's Script Tools: The 3rd Generation
#	File Description:	Resumes pendent or unfinished files to update/remove/modify
	script_version=0.6
#	Author:             Simon A. Erat (sea) <erat.simon AT gmail.com>
#	Created (y.m.d):    2011.11.01
#	Changed:            2012.08.16
#	License:            GPL v3
#
#	Title
#
	source /usr/share/script-tools/st.cfg
	sT "Yum Reset ($script_version)" 
#
#	Help
#
	[ "-h" = "$1" ] && \
		echo -e "$(basename $0) ($script_version)
		\rResets yum cache, yum pud, and yum processes.
		\r" && exit 99
	test ! "0" = "$UID" && echo "Requires root login..." && su -c "yumreset"
#
#	Variables
#
	msg="Going to clean yum cache"
#
#	Display
#
	ps -ef | grep yum | sudo awk '{ print $1 }'  | sudo xargs kill $% -9 > /dev/zero
	[ -f /var/run/yum.pid ] && \
		rm  -f /var/run/yum.pid
	yum clean all > /dev/zero
	pkill yum > /dev/zero
